import {
  WorkspaceRegistryEntry,
  JarvisWorkspaceId,
} from "./jarvisTypes";

export const workspaceRegistry: Record<JarvisWorkspaceId, WorkspaceRegistryEntry> = {
  command: {
    id: "command",
    title: "Command",
    summary: "Run natural language commands, see results, and track active runtime context.",
    icon: "Cmd",
    accent: "cyan",
    showOnHome: true,
    quickActions: ["listen", "create_daily_brief", "open_cockpit"],
    ownedFeatureBlocks: [
      "command_center",
      "latest_result",
      "conversation_thread",
      "activity_history",
      "voice_memory",
      "browser_memory",
      "recent_notes",
      "planner",
      "inbox",
      "local_files",
    ],
    relatedFloatingInspectors: ["voice"],
    advancedSettingsOwned: false,
  },
  vision: {
    id: "vision",
    title: "Vision",
    summary: "OCR reading, screen summaries, visual analysis, and OCR history.",
    icon: "Vis",
    accent: "blue",
    showOnHome: true,
    quickActions: ["read_screen", "select_ocr_area", "open_ocr_panel"],
    ownedFeatureBlocks: ["ocr_deck", "ocr_history", "screen_analysis"],
    relatedFloatingInspectors: ["ocr"],
    advancedSettingsOwned: false,
  },
  memory: {
    id: "memory",
    title: "Memory",
    summary: "People, travel, expenses, packages, meetings, school plans, and remembered context.",
    icon: "Mem",
    accent: "green",
    showOnHome: true,
    quickActions: ["create_daily_brief", "list_birthdays", "open_memory_panel"],
    ownedFeatureBlocks: [
      "people_memory",
      "travel_memory",
      "expense_memory",
      "package_memory",
      "meeting_prep_memory",
      "school_memory",
    ],
    relatedFloatingInspectors: ["memory"],
    advancedSettingsOwned: false,
  },
  automation: {
    id: "automation",
    title: "Automation",
    summary: "OCR watches, saved workflows, schedules, suggestions, and proposals.",
    icon: "Auto",
    accent: "violet",
    showOnHome: true,
    quickActions: ["show_ocr_watches", "list_desktop_schedules", "open_automation_panel"],
    ownedFeatureBlocks: [
      "ocr_watch_dashboard",
      "workflow_memory",
      "learning_proposals",
      "stored_routines",
      "cross_feature_suggestions",
      "skill_gap",
    ],
    relatedFloatingInspectors: ["automation"],
    advancedSettingsOwned: false,
  },
  workspaces: {
    id: "workspaces",
    title: "Workspaces",
    summary: "Desktop projects, schedules, and the local operating context.",
    icon: "Desk",
    accent: "amber",
    showOnHome: true,
    quickActions: ["open_coding_workspace", "list_desktop_projects", "open_workspaces_panel"],
    ownedFeatureBlocks: ["desktop_projects", "desktop_schedules", "desktop_context", "desktop_permissions"],
    relatedFloatingInspectors: ["workspaces"],
    advancedSettingsOwned: false,
  },
  connections: {
    id: "connections",
    title: "Connections",
    summary: "Google, Gmail, Notion, Spotify, Ollama, and connection health.",
    icon: "Link",
    accent: "pink",
    showOnHome: true,
    quickActions: ["show_unread_emails", "spotify_status", "open_integrations_panel"],
    ownedFeatureBlocks: [
      "google_calendar",
      "gmail",
      "notion",
      "spotify",
      "ollama",
      "local_voice",
      "local_speech",
      "wake_settings",
      "conversation_brain",
    ],
    relatedFloatingInspectors: ["integrations"],
    advancedSettingsOwned: true,
  },
  models: {
    id: "models",
    title: "Models",
    summary: "Local/cloud model routing, provider tests, benchmarks, comparisons, and safe drafts.",
    icon: "AI",
    accent: "indigo",
    showOnHome: true,
    quickActions: ["open_models_workspace", "open_system_drawer"],
    ownedFeatureBlocks: [
      "model_router",
      "provider_presets",
      "model_benchmarks",
      "model_comparisons",
      "safe_drafts",
      "private_model_mode",
    ],
    relatedFloatingInspectors: [],
    advancedSettingsOwned: true,
  },
  builder: {
    id: "builder",
    title: "Builder",
    summary: "Executor bridge, project checks, handoff packages, and local dev tooling.",
    icon: "Build",
    accent: "red",
    showOnHome: true,
    quickActions: ["run_project_checks", "open_project_in_vscode", "open_builder_panel"],
    ownedFeatureBlocks: [
      "executor_bridge",
      "project_checks",
      "handoff_package",
      "build_direction",
    ],
    relatedFloatingInspectors: ["builder"],
    advancedSettingsOwned: true,
  },
};
